apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: h1bwswy9p-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:cc75fc6d7abb3b1cf125fba134733a72748b948f@sha256:d1b61293ac41ebda7e8ad798c70e22a7ccdfe34ccb9b177fce4a49d08dbab2b7
          name: container-image
